CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522085508_InitialCreate') THEN
    CREATE TABLE "Apartments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "BlockName" text NOT NULL,
        "UnitNumber" text NOT NULL,
        "IsOccupied" boolean NOT NULL,
        "ResidentName" text NOT NULL,
        CONSTRAINT "PK_Apartments" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522085508_InitialCreate') THEN
    CREATE TABLE "Tickets" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" text NOT NULL,
        "Description" text NOT NULL,
        "Status" text NOT NULL,
        "Priority" text NOT NULL,
        "AssignedTo" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Tickets" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522085508_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260522085508_InitialCreate', '10.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151149_NormalizedSchema') THEN
    ALTER TABLE "Apartments" DROP COLUMN "ResidentName";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151149_NormalizedSchema') THEN
    ALTER TABLE "Apartments" ADD "BuilderId" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151149_NormalizedSchema') THEN
    CREATE TABLE "Builders" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CompanyName" text NOT NULL,
        "ContactEmail" text NOT NULL,
        CONSTRAINT "PK_Builders" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151149_NormalizedSchema') THEN
    CREATE TABLE "Managers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FirstName" text NOT NULL,
        "LastName" text NOT NULL,
        "KeycloakUserId" text NOT NULL,
        CONSTRAINT "PK_Managers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151149_NormalizedSchema') THEN
    CREATE TABLE "Residents" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FirstName" text NOT NULL,
        "LastName" text NOT NULL,
        "KeycloakUserId" text NOT NULL,
        "ApartmentId" integer NOT NULL,
        CONSTRAINT "PK_Residents" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Residents_Apartments_ApartmentId" FOREIGN KEY ("ApartmentId") REFERENCES "Apartments" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151149_NormalizedSchema') THEN
    CREATE TABLE "ApartmentManagers" (
        "ApartmentsId" integer NOT NULL,
        "ManagersId" integer NOT NULL,
        CONSTRAINT "PK_ApartmentManagers" PRIMARY KEY ("ApartmentsId", "ManagersId"),
        CONSTRAINT "FK_ApartmentManagers_Apartments_ApartmentsId" FOREIGN KEY ("ApartmentsId") REFERENCES "Apartments" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ApartmentManagers_Managers_ManagersId" FOREIGN KEY ("ManagersId") REFERENCES "Managers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151149_NormalizedSchema') THEN
    CREATE INDEX "IX_Apartments_BuilderId" ON "Apartments" ("BuilderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151149_NormalizedSchema') THEN
    CREATE INDEX "IX_ApartmentManagers_ManagersId" ON "ApartmentManagers" ("ManagersId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151149_NormalizedSchema') THEN
    CREATE INDEX "IX_Residents_ApartmentId" ON "Residents" ("ApartmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151149_NormalizedSchema') THEN
    ALTER TABLE "Apartments" ADD CONSTRAINT "FK_Apartments_Builders_BuilderId" FOREIGN KEY ("BuilderId") REFERENCES "Builders" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151149_NormalizedSchema') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260522151149_NormalizedSchema', '10.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151609_SeedSampleData') THEN
    INSERT INTO "Builders" ("Id", "CompanyName", "ContactEmail")
    VALUES (1, 'Aura Properties', 'contact@auraproperties.com');
    INSERT INTO "Builders" ("Id", "CompanyName", "ContactEmail")
    VALUES (2, 'Skyline Dev', 'hello@skylinedev.com');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151609_SeedSampleData') THEN
    INSERT INTO "Managers" ("Id", "FirstName", "KeycloakUserId", "LastName")
    VALUES (1, 'Alice', 'alice-manager-uuid', 'Johnson');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151609_SeedSampleData') THEN
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (1, 'Block A', 1, TRUE, '101');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (2, 'Block B', 1, FALSE, '205');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (3, 'Tower C', 2, TRUE, 'Penthouse 1');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151609_SeedSampleData') THEN
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (1, 1);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (2, 1);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151609_SeedSampleData') THEN
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (1, 1, 'John', 'john-sso-uuid', 'Doe');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (2, 3, 'Jane', 'jane-sso-uuid', 'Smith');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151609_SeedSampleData') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Builders"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Builders") + 1,
            nextval(pg_get_serial_sequence('"Builders"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"Managers"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Managers") + 1,
            nextval(pg_get_serial_sequence('"Managers"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"Apartments"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Apartments") + 1,
            nextval(pg_get_serial_sequence('"Apartments"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"Residents"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Residents") + 1,
            nextval(pg_get_serial_sequence('"Residents"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151609_SeedSampleData') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260522151609_SeedSampleData', '10.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151931_SeedBulkData') THEN
    DELETE FROM "ApartmentManagers"
    WHERE "ApartmentsId" = 1 AND "ManagersId" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151931_SeedBulkData') THEN
    DELETE FROM "ApartmentManagers"
    WHERE "ApartmentsId" = 2 AND "ManagersId" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151931_SeedBulkData') THEN
    UPDATE "Apartments" SET "BlockName" = 'Block A', "IsOccupied" = TRUE, "UnitNumber" = '202'
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151931_SeedBulkData') THEN
    UPDATE "Apartments" SET "BlockName" = 'Block A', "BuilderId" = 1, "UnitNumber" = '303'
    WHERE "Id" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151931_SeedBulkData') THEN
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (4, 'Block A', 1, TRUE, '404');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (5, 'Block A', 1, TRUE, '505');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (6, 'Block A', 1, TRUE, '606');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (7, 'Block A', 1, TRUE, '707');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (8, 'Block A', 1, TRUE, '808');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (9, 'Block A', 1, TRUE, '909');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (10, 'Block A', 1, TRUE, '10010');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (11, 'Block A', 1, TRUE, '11011');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (12, 'Block A', 1, TRUE, '12012');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (13, 'Block A', 1, TRUE, '13013');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (14, 'Block A', 1, TRUE, '14014');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (15, 'Block A', 1, TRUE, '15015');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (16, 'Block B', 2, TRUE, '101');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (17, 'Block B', 2, TRUE, '202');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (18, 'Block B', 2, TRUE, '303');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (19, 'Block B', 2, TRUE, '404');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (20, 'Block B', 2, TRUE, '505');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (21, 'Block B', 2, TRUE, '606');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (22, 'Block B', 2, TRUE, '707');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (23, 'Block B', 2, TRUE, '808');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (24, 'Block B', 2, TRUE, '909');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (25, 'Block B', 2, TRUE, '10010');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (26, 'Block B', 2, TRUE, '11011');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (27, 'Block B', 2, TRUE, '12012');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (28, 'Block B', 2, TRUE, '13013');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (29, 'Block B', 2, TRUE, '14014');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (30, 'Block B', 2, TRUE, '15015');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151931_SeedBulkData') THEN
    INSERT INTO "Builders" ("Id", "CompanyName", "ContactEmail")
    VALUES (3, 'Pinnacle Real Estate', 'info@pinnacle.com');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151931_SeedBulkData') THEN
    UPDATE "Managers" SET "FirstName" = 'Manager1First', "KeycloakUserId" = 'manager-1-sso-uuid', "LastName" = 'Manager1Last'
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151931_SeedBulkData') THEN
    INSERT INTO "Managers" ("Id", "FirstName", "KeycloakUserId", "LastName")
    VALUES (2, 'Manager2First', 'manager-2-sso-uuid', 'Manager2Last');
    INSERT INTO "Managers" ("Id", "FirstName", "KeycloakUserId", "LastName")
    VALUES (3, 'Manager3First', 'manager-3-sso-uuid', 'Manager3Last');
    INSERT INTO "Managers" ("Id", "FirstName", "KeycloakUserId", "LastName")
    VALUES (4, 'Manager4First', 'manager-4-sso-uuid', 'Manager4Last');
    INSERT INTO "Managers" ("Id", "FirstName", "KeycloakUserId", "LastName")
    VALUES (5, 'Manager5First', 'manager-5-sso-uuid', 'Manager5Last');
    INSERT INTO "Managers" ("Id", "FirstName", "KeycloakUserId", "LastName")
    VALUES (6, 'Manager6First', 'manager-6-sso-uuid', 'Manager6Last');
    INSERT INTO "Managers" ("Id", "FirstName", "KeycloakUserId", "LastName")
    VALUES (7, 'Manager7First', 'manager-7-sso-uuid', 'Manager7Last');
    INSERT INTO "Managers" ("Id", "FirstName", "KeycloakUserId", "LastName")
    VALUES (8, 'Manager8First', 'manager-8-sso-uuid', 'Manager8Last');
    INSERT INTO "Managers" ("Id", "FirstName", "KeycloakUserId", "LastName")
    VALUES (9, 'Manager9First', 'manager-9-sso-uuid', 'Manager9Last');
    INSERT INTO "Managers" ("Id", "FirstName", "KeycloakUserId", "LastName")
    VALUES (10, 'Manager10First', 'manager-10-sso-uuid', 'Manager10Last');
    INSERT INTO "Managers" ("Id", "FirstName", "KeycloakUserId", "LastName")
    VALUES (11, 'Manager11First', 'manager-11-sso-uuid', 'Manager11Last');
    INSERT INTO "Managers" ("Id", "FirstName", "KeycloakUserId", "LastName")
    VALUES (12, 'Manager12First', 'manager-12-sso-uuid', 'Manager12Last');
    INSERT INTO "Managers" ("Id", "FirstName", "KeycloakUserId", "LastName")
    VALUES (13, 'Manager13First', 'manager-13-sso-uuid', 'Manager13Last');
    INSERT INTO "Managers" ("Id", "FirstName", "KeycloakUserId", "LastName")
    VALUES (14, 'Manager14First', 'manager-14-sso-uuid', 'Manager14Last');
    INSERT INTO "Managers" ("Id", "FirstName", "KeycloakUserId", "LastName")
    VALUES (15, 'Manager15First', 'manager-15-sso-uuid', 'Manager15Last');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151931_SeedBulkData') THEN
    UPDATE "Residents" SET "FirstName" = 'Resident2First', "KeycloakUserId" = 'resident-2-sso-uuid', "LastName" = 'Resident2Last'
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151931_SeedBulkData') THEN
    UPDATE "Residents" SET "ApartmentId" = 2, "FirstName" = 'Resident3First', "KeycloakUserId" = 'resident-3-sso-uuid', "LastName" = 'Resident3Last'
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151931_SeedBulkData') THEN
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (3, 3, 'Resident4First', 'resident-4-sso-uuid', 'Resident4Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (4, 3, 'Resident5First', 'resident-5-sso-uuid', 'Resident5Last');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151931_SeedBulkData') THEN
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (1, 2);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (2, 3);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (3, 4);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (4, 5);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (4, 6);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (5, 1);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (6, 2);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (7, 3);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (8, 4);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (8, 5);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (9, 5);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (10, 1);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (11, 2);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (12, 3);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (12, 4);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (13, 4);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (14, 5);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (15, 1);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (16, 7);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (16, 8);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (17, 8);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (18, 9);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (19, 10);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (20, 6);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (20, 7);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (21, 7);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (22, 8);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (23, 9);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (24, 10);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (24, 11);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (25, 6);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (26, 7);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (27, 8);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (28, 9);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (28, 10);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (29, 10);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (30, 6);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151931_SeedBulkData') THEN
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (31, 'Block C', 3, TRUE, '101');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (32, 'Block C', 3, TRUE, '202');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (33, 'Block C', 3, TRUE, '303');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (34, 'Block C', 3, TRUE, '404');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (35, 'Block C', 3, TRUE, '505');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (36, 'Block C', 3, TRUE, '606');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (37, 'Block C', 3, TRUE, '707');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (38, 'Block C', 3, TRUE, '808');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (39, 'Block C', 3, TRUE, '909');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (40, 'Block C', 3, TRUE, '10010');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (41, 'Block C', 3, TRUE, '11011');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (42, 'Block C', 3, TRUE, '12012');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (43, 'Block C', 3, TRUE, '13013');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (44, 'Block C', 3, TRUE, '14014');
    INSERT INTO "Apartments" ("Id", "BlockName", "BuilderId", "IsOccupied", "UnitNumber")
    VALUES (45, 'Block C', 3, TRUE, '15015');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151931_SeedBulkData') THEN
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (5, 4, 'Resident6First', 'resident-6-sso-uuid', 'Resident6Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (6, 5, 'Resident7First', 'resident-7-sso-uuid', 'Resident7Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (7, 6, 'Resident8First', 'resident-8-sso-uuid', 'Resident8Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (8, 6, 'Resident9First', 'resident-9-sso-uuid', 'Resident9Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (9, 7, 'Resident10First', 'resident-10-sso-uuid', 'Resident10Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (10, 8, 'Resident11First', 'resident-11-sso-uuid', 'Resident11Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (11, 9, 'Resident12First', 'resident-12-sso-uuid', 'Resident12Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (12, 9, 'Resident13First', 'resident-13-sso-uuid', 'Resident13Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (13, 10, 'Resident14First', 'resident-14-sso-uuid', 'Resident14Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (14, 11, 'Resident15First', 'resident-15-sso-uuid', 'Resident15Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (15, 12, 'Resident16First', 'resident-16-sso-uuid', 'Resident16Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (16, 12, 'Resident17First', 'resident-17-sso-uuid', 'Resident17Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (17, 13, 'Resident18First', 'resident-18-sso-uuid', 'Resident18Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (18, 14, 'Resident19First', 'resident-19-sso-uuid', 'Resident19Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (19, 15, 'Resident20First', 'resident-20-sso-uuid', 'Resident20Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (20, 15, 'Resident21First', 'resident-21-sso-uuid', 'Resident21Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (21, 16, 'Resident22First', 'resident-22-sso-uuid', 'Resident22Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (22, 17, 'Resident23First', 'resident-23-sso-uuid', 'Resident23Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (23, 18, 'Resident24First', 'resident-24-sso-uuid', 'Resident24Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (24, 18, 'Resident25First', 'resident-25-sso-uuid', 'Resident25Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (25, 19, 'Resident26First', 'resident-26-sso-uuid', 'Resident26Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (26, 20, 'Resident27First', 'resident-27-sso-uuid', 'Resident27Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (27, 21, 'Resident28First', 'resident-28-sso-uuid', 'Resident28Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (28, 21, 'Resident29First', 'resident-29-sso-uuid', 'Resident29Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (29, 22, 'Resident30First', 'resident-30-sso-uuid', 'Resident30Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (30, 23, 'Resident31First', 'resident-31-sso-uuid', 'Resident31Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (31, 24, 'Resident32First', 'resident-32-sso-uuid', 'Resident32Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (32, 24, 'Resident33First', 'resident-33-sso-uuid', 'Resident33Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (33, 25, 'Resident34First', 'resident-34-sso-uuid', 'Resident34Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (34, 26, 'Resident35First', 'resident-35-sso-uuid', 'Resident35Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (35, 27, 'Resident36First', 'resident-36-sso-uuid', 'Resident36Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (36, 27, 'Resident37First', 'resident-37-sso-uuid', 'Resident37Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (37, 28, 'Resident38First', 'resident-38-sso-uuid', 'Resident38Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (38, 29, 'Resident39First', 'resident-39-sso-uuid', 'Resident39Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (39, 30, 'Resident40First', 'resident-40-sso-uuid', 'Resident40Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (40, 30, 'Resident41First', 'resident-41-sso-uuid', 'Resident41Last');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151931_SeedBulkData') THEN
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (31, 12);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (32, 13);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (32, 14);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (33, 14);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (34, 15);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (35, 11);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (36, 12);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (36, 13);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (37, 13);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (38, 14);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (39, 15);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (40, 11);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (40, 12);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (41, 12);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (42, 13);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (43, 14);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (44, 1);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (44, 15);
    INSERT INTO "ApartmentManagers" ("ApartmentsId", "ManagersId")
    VALUES (45, 11);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151931_SeedBulkData') THEN
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (41, 31, 'Resident42First', 'resident-42-sso-uuid', 'Resident42Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (42, 32, 'Resident43First', 'resident-43-sso-uuid', 'Resident43Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (43, 33, 'Resident44First', 'resident-44-sso-uuid', 'Resident44Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (44, 33, 'Resident45First', 'resident-45-sso-uuid', 'Resident45Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (45, 34, 'Resident46First', 'resident-46-sso-uuid', 'Resident46Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (46, 35, 'Resident47First', 'resident-47-sso-uuid', 'Resident47Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (47, 36, 'Resident48First', 'resident-48-sso-uuid', 'Resident48Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (48, 36, 'Resident49First', 'resident-49-sso-uuid', 'Resident49Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (49, 37, 'Resident50First', 'resident-50-sso-uuid', 'Resident50Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (50, 38, 'Resident51First', 'resident-51-sso-uuid', 'Resident51Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (51, 39, 'Resident52First', 'resident-52-sso-uuid', 'Resident52Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (52, 39, 'Resident53First', 'resident-53-sso-uuid', 'Resident53Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (53, 40, 'Resident54First', 'resident-54-sso-uuid', 'Resident54Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (54, 41, 'Resident55First', 'resident-55-sso-uuid', 'Resident55Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (55, 42, 'Resident56First', 'resident-56-sso-uuid', 'Resident56Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (56, 42, 'Resident57First', 'resident-57-sso-uuid', 'Resident57Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (57, 43, 'Resident58First', 'resident-58-sso-uuid', 'Resident58Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (58, 44, 'Resident59First', 'resident-59-sso-uuid', 'Resident59Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (59, 45, 'Resident60First', 'resident-60-sso-uuid', 'Resident60Last');
    INSERT INTO "Residents" ("Id", "ApartmentId", "FirstName", "KeycloakUserId", "LastName")
    VALUES (60, 45, 'Resident61First', 'resident-61-sso-uuid', 'Resident61Last');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151931_SeedBulkData') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Apartments"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Apartments") + 1,
            nextval(pg_get_serial_sequence('"Apartments"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"Builders"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Builders") + 1,
            nextval(pg_get_serial_sequence('"Builders"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"Managers"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Managers") + 1,
            nextval(pg_get_serial_sequence('"Managers"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"Residents"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Residents") + 1,
            nextval(pg_get_serial_sequence('"Residents"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522151931_SeedBulkData') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260522151931_SeedBulkData', '10.0.8');
    END IF;
END $EF$;
COMMIT;

