// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VastGrid.Server.Data;

#nullable disable

namespace VastGrid.Server.Migrations
{
    [DbContext(typeof(VastGridDbContext))]
    [Migration("20260522151931_SeedBulkData")]
    partial class SeedBulkData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApartmentManager", b =>
                {
                    b.Property<int>("ApartmentsId")
                        .HasColumnType("integer");

                    b.Property<int>("ManagersId")
                        .HasColumnType("integer");

                    b.HasKey("ApartmentsId", "ManagersId");

                    b.HasIndex("ManagersId");

                    b.ToTable("ApartmentManagers", (string)null);

                    b.HasData(
                        new
                        {
                            ApartmentsId = 1,
                            ManagersId = 2
                        },
                        new
                        {
                            ApartmentsId = 2,
                            ManagersId = 3
                        },
                        new
                        {
                            ApartmentsId = 3,
                            ManagersId = 4
                        },
                        new
                        {
                            ApartmentsId = 4,
                            ManagersId = 5
                        },
                        new
                        {
                            ApartmentsId = 4,
                            ManagersId = 6
                        },
                        new
                        {
                            ApartmentsId = 5,
                            ManagersId = 1
                        },
                        new
                        {
                            ApartmentsId = 6,
                            ManagersId = 2
                        },
                        new
                        {
                            ApartmentsId = 7,
                            ManagersId = 3
                        },
                        new
                        {
                            ApartmentsId = 8,
                            ManagersId = 4
                        },
                        new
                        {
                            ApartmentsId = 8,
                            ManagersId = 5
                        },
                        new
                        {
                            ApartmentsId = 9,
                            ManagersId = 5
                        },
                        new
                        {
                            ApartmentsId = 10,
                            ManagersId = 1
                        },
                        new
                        {
                            ApartmentsId = 11,
                            ManagersId = 2
                        },
                        new
                        {
                            ApartmentsId = 12,
                            ManagersId = 3
                        },
                        new
                        {
                            ApartmentsId = 12,
                            ManagersId = 4
                        },
                        new
                        {
                            ApartmentsId = 13,
                            ManagersId = 4
                        },
                        new
                        {
                            ApartmentsId = 14,
                            ManagersId = 5
                        },
                        new
                        {
                            ApartmentsId = 15,
                            ManagersId = 1
                        },
                        new
                        {
                            ApartmentsId = 16,
                            ManagersId = 7
                        },
                        new
                        {
                            ApartmentsId = 16,
                            ManagersId = 8
                        },
                        new
                        {
                            ApartmentsId = 17,
                            ManagersId = 8
                        },
                        new
                        {
                            ApartmentsId = 18,
                            ManagersId = 9
                        },
                        new
                        {
                            ApartmentsId = 19,
                            ManagersId = 10
                        },
                        new
                        {
                            ApartmentsId = 20,
                            ManagersId = 6
                        },
                        new
                        {
                            ApartmentsId = 20,
                            ManagersId = 7
                        },
                        new
                        {
                            ApartmentsId = 21,
                            ManagersId = 7
                        },
                        new
                        {
                            ApartmentsId = 22,
                            ManagersId = 8
                        },
                        new
                        {
                            ApartmentsId = 23,
                            ManagersId = 9
                        },
                        new
                        {
                            ApartmentsId = 24,
                            ManagersId = 10
                        },
                        new
                        {
                            ApartmentsId = 24,
                            ManagersId = 11
                        },
                        new
                        {
                            ApartmentsId = 25,
                            ManagersId = 6
                        },
                        new
                        {
                            ApartmentsId = 26,
                            ManagersId = 7
                        },
                        new
                        {
                            ApartmentsId = 27,
                            ManagersId = 8
                        },
                        new
                        {
                            ApartmentsId = 28,
                            ManagersId = 9
                        },
                        new
                        {
                            ApartmentsId = 28,
                            ManagersId = 10
                        },
                        new
                        {
                            ApartmentsId = 29,
                            ManagersId = 10
                        },
                        new
                        {
                            ApartmentsId = 30,
                            ManagersId = 6
                        },
                        new
                        {
                            ApartmentsId = 31,
                            ManagersId = 12
                        },
                        new
                        {
                            ApartmentsId = 32,
                            ManagersId = 13
                        },
                        new
                        {
                            ApartmentsId = 32,
                            ManagersId = 14
                        },
                        new
                        {
                            ApartmentsId = 33,
                            ManagersId = 14
                        },
                        new
                        {
                            ApartmentsId = 34,
                            ManagersId = 15
                        },
                        new
                        {
                            ApartmentsId = 35,
                            ManagersId = 11
                        },
                        new
                        {
                            ApartmentsId = 36,
                            ManagersId = 12
                        },
                        new
                        {
                            ApartmentsId = 36,
                            ManagersId = 13
                        },
                        new
                        {
                            ApartmentsId = 37,
                            ManagersId = 13
                        },
                        new
                        {
                            ApartmentsId = 38,
                            ManagersId = 14
                        },
                        new
                        {
                            ApartmentsId = 39,
                            ManagersId = 15
                        },
                        new
                        {
                            ApartmentsId = 40,
                            ManagersId = 11
                        },
                        new
                        {
                            ApartmentsId = 40,
                            ManagersId = 12
                        },
                        new
                        {
                            ApartmentsId = 41,
                            ManagersId = 12
                        },
                        new
                        {
                            ApartmentsId = 42,
                            ManagersId = 13
                        },
                        new
                        {
                            ApartmentsId = 43,
                            ManagersId = 14
                        },
                        new
                        {
                            ApartmentsId = 44,
                            ManagersId = 15
                        },
                        new
                        {
                            ApartmentsId = 44,
                            ManagersId = 1
                        },
                        new
                        {
                            ApartmentsId = 45,
                            ManagersId = 11
                        });
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BlockName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BuilderId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("boolean");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BuilderId");

                    b.ToTable("Apartments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlockName = "Block A",
                            BuilderId = 1,
                            IsOccupied = true,
                            UnitNumber = "101"
                        },
                        new
                        {
                            Id = 2,
                            BlockName = "Block A",
                            BuilderId = 1,
                            IsOccupied = true,
                            UnitNumber = "202"
                        },
                        new
                        {
                            Id = 3,
                            BlockName = "Block A",
                            BuilderId = 1,
                            IsOccupied = true,
                            UnitNumber = "303"
                        },
                        new
                        {
                            Id = 4,
                            BlockName = "Block A",
                            BuilderId = 1,
                            IsOccupied = true,
                            UnitNumber = "404"
                        },
                        new
                        {
                            Id = 5,
                            BlockName = "Block A",
                            BuilderId = 1,
                            IsOccupied = true,
                            UnitNumber = "505"
                        },
                        new
                        {
                            Id = 6,
                            BlockName = "Block A",
                            BuilderId = 1,
                            IsOccupied = true,
                            UnitNumber = "606"
                        },
                        new
                        {
                            Id = 7,
                            BlockName = "Block A",
                            BuilderId = 1,
                            IsOccupied = true,
                            UnitNumber = "707"
                        },
                        new
                        {
                            Id = 8,
                            BlockName = "Block A",
                            BuilderId = 1,
                            IsOccupied = true,
                            UnitNumber = "808"
                        },
                        new
                        {
                            Id = 9,
                            BlockName = "Block A",
                            BuilderId = 1,
                            IsOccupied = true,
                            UnitNumber = "909"
                        },
                        new
                        {
                            Id = 10,
                            BlockName = "Block A",
                            BuilderId = 1,
                            IsOccupied = true,
                            UnitNumber = "10010"
                        },
                        new
                        {
                            Id = 11,
                            BlockName = "Block A",
                            BuilderId = 1,
                            IsOccupied = true,
                            UnitNumber = "11011"
                        },
                        new
                        {
                            Id = 12,
                            BlockName = "Block A",
                            BuilderId = 1,
                            IsOccupied = true,
                            UnitNumber = "12012"
                        },
                        new
                        {
                            Id = 13,
                            BlockName = "Block A",
                            BuilderId = 1,
                            IsOccupied = true,
                            UnitNumber = "13013"
                        },
                        new
                        {
                            Id = 14,
                            BlockName = "Block A",
                            BuilderId = 1,
                            IsOccupied = true,
                            UnitNumber = "14014"
                        },
                        new
                        {
                            Id = 15,
                            BlockName = "Block A",
                            BuilderId = 1,
                            IsOccupied = true,
                            UnitNumber = "15015"
                        },
                        new
                        {
                            Id = 16,
                            BlockName = "Block B",
                            BuilderId = 2,
                            IsOccupied = true,
                            UnitNumber = "101"
                        },
                        new
                        {
                            Id = 17,
                            BlockName = "Block B",
                            BuilderId = 2,
                            IsOccupied = true,
                            UnitNumber = "202"
                        },
                        new
                        {
                            Id = 18,
                            BlockName = "Block B",
                            BuilderId = 2,
                            IsOccupied = true,
                            UnitNumber = "303"
                        },
                        new
                        {
                            Id = 19,
                            BlockName = "Block B",
                            BuilderId = 2,
                            IsOccupied = true,
                            UnitNumber = "404"
                        },
                        new
                        {
                            Id = 20,
                            BlockName = "Block B",
                            BuilderId = 2,
                            IsOccupied = true,
                            UnitNumber = "505"
                        },
                        new
                        {
                            Id = 21,
                            BlockName = "Block B",
                            BuilderId = 2,
                            IsOccupied = true,
                            UnitNumber = "606"
                        },
                        new
                        {
                            Id = 22,
                            BlockName = "Block B",
                            BuilderId = 2,
                            IsOccupied = true,
                            UnitNumber = "707"
                        },
                        new
                        {
                            Id = 23,
                            BlockName = "Block B",
                            BuilderId = 2,
                            IsOccupied = true,
                            UnitNumber = "808"
                        },
                        new
                        {
                            Id = 24,
                            BlockName = "Block B",
                            BuilderId = 2,
                            IsOccupied = true,
                            UnitNumber = "909"
                        },
                        new
                        {
                            Id = 25,
                            BlockName = "Block B",
                            BuilderId = 2,
                            IsOccupied = true,
                            UnitNumber = "10010"
                        },
                        new
                        {
                            Id = 26,
                            BlockName = "Block B",
                            BuilderId = 2,
                            IsOccupied = true,
                            UnitNumber = "11011"
                        },
                        new
                        {
                            Id = 27,
                            BlockName = "Block B",
                            BuilderId = 2,
                            IsOccupied = true,
                            UnitNumber = "12012"
                        },
                        new
                        {
                            Id = 28,
                            BlockName = "Block B",
                            BuilderId = 2,
                            IsOccupied = true,
                            UnitNumber = "13013"
                        },
                        new
                        {
                            Id = 29,
                            BlockName = "Block B",
                            BuilderId = 2,
                            IsOccupied = true,
                            UnitNumber = "14014"
                        },
                        new
                        {
                            Id = 30,
                            BlockName = "Block B",
                            BuilderId = 2,
                            IsOccupied = true,
                            UnitNumber = "15015"
                        },
                        new
                        {
                            Id = 31,
                            BlockName = "Block C",
                            BuilderId = 3,
                            IsOccupied = true,
                            UnitNumber = "101"
                        },
                        new
                        {
                            Id = 32,
                            BlockName = "Block C",
                            BuilderId = 3,
                            IsOccupied = true,
                            UnitNumber = "202"
                        },
                        new
                        {
                            Id = 33,
                            BlockName = "Block C",
                            BuilderId = 3,
                            IsOccupied = true,
                            UnitNumber = "303"
                        },
                        new
                        {
                            Id = 34,
                            BlockName = "Block C",
                            BuilderId = 3,
                            IsOccupied = true,
                            UnitNumber = "404"
                        },
                        new
                        {
                            Id = 35,
                            BlockName = "Block C",
                            BuilderId = 3,
                            IsOccupied = true,
                            UnitNumber = "505"
                        },
                        new
                        {
                            Id = 36,
                            BlockName = "Block C",
                            BuilderId = 3,
                            IsOccupied = true,
                            UnitNumber = "606"
                        },
                        new
                        {
                            Id = 37,
                            BlockName = "Block C",
                            BuilderId = 3,
                            IsOccupied = true,
                            UnitNumber = "707"
                        },
                        new
                        {
                            Id = 38,
                            BlockName = "Block C",
                            BuilderId = 3,
                            IsOccupied = true,
                            UnitNumber = "808"
                        },
                        new
                        {
                            Id = 39,
                            BlockName = "Block C",
                            BuilderId = 3,
                            IsOccupied = true,
                            UnitNumber = "909"
                        },
                        new
                        {
                            Id = 40,
                            BlockName = "Block C",
                            BuilderId = 3,
                            IsOccupied = true,
                            UnitNumber = "10010"
                        },
                        new
                        {
                            Id = 41,
                            BlockName = "Block C",
                            BuilderId = 3,
                            IsOccupied = true,
                            UnitNumber = "11011"
                        },
                        new
                        {
                            Id = 42,
                            BlockName = "Block C",
                            BuilderId = 3,
                            IsOccupied = true,
                            UnitNumber = "12012"
                        },
                        new
                        {
                            Id = 43,
                            BlockName = "Block C",
                            BuilderId = 3,
                            IsOccupied = true,
                            UnitNumber = "13013"
                        },
                        new
                        {
                            Id = 44,
                            BlockName = "Block C",
                            BuilderId = 3,
                            IsOccupied = true,
                            UnitNumber = "14014"
                        },
                        new
                        {
                            Id = 45,
                            BlockName = "Block C",
                            BuilderId = 3,
                            IsOccupied = true,
                            UnitNumber = "15015"
                        });
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.Builder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Builders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Aura Properties",
                            ContactEmail = "contact@auraproperties.com"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Skyline Dev",
                            ContactEmail = "hello@skylinedev.com"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Pinnacle Real Estate",
                            ContactEmail = "info@pinnacle.com"
                        });
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeycloakUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Manager1First",
                            KeycloakUserId = "manager-1-sso-uuid",
                            LastName = "Manager1Last"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Manager2First",
                            KeycloakUserId = "manager-2-sso-uuid",
                            LastName = "Manager2Last"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Manager3First",
                            KeycloakUserId = "manager-3-sso-uuid",
                            LastName = "Manager3Last"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Manager4First",
                            KeycloakUserId = "manager-4-sso-uuid",
                            LastName = "Manager4Last"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Manager5First",
                            KeycloakUserId = "manager-5-sso-uuid",
                            LastName = "Manager5Last"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Manager6First",
                            KeycloakUserId = "manager-6-sso-uuid",
                            LastName = "Manager6Last"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Manager7First",
                            KeycloakUserId = "manager-7-sso-uuid",
                            LastName = "Manager7Last"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Manager8First",
                            KeycloakUserId = "manager-8-sso-uuid",
                            LastName = "Manager8Last"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Manager9First",
                            KeycloakUserId = "manager-9-sso-uuid",
                            LastName = "Manager9Last"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Manager10First",
                            KeycloakUserId = "manager-10-sso-uuid",
                            LastName = "Manager10Last"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Manager11First",
                            KeycloakUserId = "manager-11-sso-uuid",
                            LastName = "Manager11Last"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Manager12First",
                            KeycloakUserId = "manager-12-sso-uuid",
                            LastName = "Manager12Last"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Manager13First",
                            KeycloakUserId = "manager-13-sso-uuid",
                            LastName = "Manager13Last"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Manager14First",
                            KeycloakUserId = "manager-14-sso-uuid",
                            LastName = "Manager14Last"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Manager15First",
                            KeycloakUserId = "manager-15-sso-uuid",
                            LastName = "Manager15Last"
                        });
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.Resident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeycloakUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.ToTable("Residents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApartmentId = 1,
                            FirstName = "Resident2First",
                            KeycloakUserId = "resident-2-sso-uuid",
                            LastName = "Resident2Last"
                        },
                        new
                        {
                            Id = 2,
                            ApartmentId = 2,
                            FirstName = "Resident3First",
                            KeycloakUserId = "resident-3-sso-uuid",
                            LastName = "Resident3Last"
                        },
                        new
                        {
                            Id = 3,
                            ApartmentId = 3,
                            FirstName = "Resident4First",
                            KeycloakUserId = "resident-4-sso-uuid",
                            LastName = "Resident4Last"
                        },
                        new
                        {
                            Id = 4,
                            ApartmentId = 3,
                            FirstName = "Resident5First",
                            KeycloakUserId = "resident-5-sso-uuid",
                            LastName = "Resident5Last"
                        },
                        new
                        {
                            Id = 5,
                            ApartmentId = 4,
                            FirstName = "Resident6First",
                            KeycloakUserId = "resident-6-sso-uuid",
                            LastName = "Resident6Last"
                        },
                        new
                        {
                            Id = 6,
                            ApartmentId = 5,
                            FirstName = "Resident7First",
                            KeycloakUserId = "resident-7-sso-uuid",
                            LastName = "Resident7Last"
                        },
                        new
                        {
                            Id = 7,
                            ApartmentId = 6,
                            FirstName = "Resident8First",
                            KeycloakUserId = "resident-8-sso-uuid",
                            LastName = "Resident8Last"
                        },
                        new
                        {
                            Id = 8,
                            ApartmentId = 6,
                            FirstName = "Resident9First",
                            KeycloakUserId = "resident-9-sso-uuid",
                            LastName = "Resident9Last"
                        },
                        new
                        {
                            Id = 9,
                            ApartmentId = 7,
                            FirstName = "Resident10First",
                            KeycloakUserId = "resident-10-sso-uuid",
                            LastName = "Resident10Last"
                        },
                        new
                        {
                            Id = 10,
                            ApartmentId = 8,
                            FirstName = "Resident11First",
                            KeycloakUserId = "resident-11-sso-uuid",
                            LastName = "Resident11Last"
                        },
                        new
                        {
                            Id = 11,
                            ApartmentId = 9,
                            FirstName = "Resident12First",
                            KeycloakUserId = "resident-12-sso-uuid",
                            LastName = "Resident12Last"
                        },
                        new
                        {
                            Id = 12,
                            ApartmentId = 9,
                            FirstName = "Resident13First",
                            KeycloakUserId = "resident-13-sso-uuid",
                            LastName = "Resident13Last"
                        },
                        new
                        {
                            Id = 13,
                            ApartmentId = 10,
                            FirstName = "Resident14First",
                            KeycloakUserId = "resident-14-sso-uuid",
                            LastName = "Resident14Last"
                        },
                        new
                        {
                            Id = 14,
                            ApartmentId = 11,
                            FirstName = "Resident15First",
                            KeycloakUserId = "resident-15-sso-uuid",
                            LastName = "Resident15Last"
                        },
                        new
                        {
                            Id = 15,
                            ApartmentId = 12,
                            FirstName = "Resident16First",
                            KeycloakUserId = "resident-16-sso-uuid",
                            LastName = "Resident16Last"
                        },
                        new
                        {
                            Id = 16,
                            ApartmentId = 12,
                            FirstName = "Resident17First",
                            KeycloakUserId = "resident-17-sso-uuid",
                            LastName = "Resident17Last"
                        },
                        new
                        {
                            Id = 17,
                            ApartmentId = 13,
                            FirstName = "Resident18First",
                            KeycloakUserId = "resident-18-sso-uuid",
                            LastName = "Resident18Last"
                        },
                        new
                        {
                            Id = 18,
                            ApartmentId = 14,
                            FirstName = "Resident19First",
                            KeycloakUserId = "resident-19-sso-uuid",
                            LastName = "Resident19Last"
                        },
                        new
                        {
                            Id = 19,
                            ApartmentId = 15,
                            FirstName = "Resident20First",
                            KeycloakUserId = "resident-20-sso-uuid",
                            LastName = "Resident20Last"
                        },
                        new
                        {
                            Id = 20,
                            ApartmentId = 15,
                            FirstName = "Resident21First",
                            KeycloakUserId = "resident-21-sso-uuid",
                            LastName = "Resident21Last"
                        },
                        new
                        {
                            Id = 21,
                            ApartmentId = 16,
                            FirstName = "Resident22First",
                            KeycloakUserId = "resident-22-sso-uuid",
                            LastName = "Resident22Last"
                        },
                        new
                        {
                            Id = 22,
                            ApartmentId = 17,
                            FirstName = "Resident23First",
                            KeycloakUserId = "resident-23-sso-uuid",
                            LastName = "Resident23Last"
                        },
                        new
                        {
                            Id = 23,
                            ApartmentId = 18,
                            FirstName = "Resident24First",
                            KeycloakUserId = "resident-24-sso-uuid",
                            LastName = "Resident24Last"
                        },
                        new
                        {
                            Id = 24,
                            ApartmentId = 18,
                            FirstName = "Resident25First",
                            KeycloakUserId = "resident-25-sso-uuid",
                            LastName = "Resident25Last"
                        },
                        new
                        {
                            Id = 25,
                            ApartmentId = 19,
                            FirstName = "Resident26First",
                            KeycloakUserId = "resident-26-sso-uuid",
                            LastName = "Resident26Last"
                        },
                        new
                        {
                            Id = 26,
                            ApartmentId = 20,
                            FirstName = "Resident27First",
                            KeycloakUserId = "resident-27-sso-uuid",
                            LastName = "Resident27Last"
                        },
                        new
                        {
                            Id = 27,
                            ApartmentId = 21,
                            FirstName = "Resident28First",
                            KeycloakUserId = "resident-28-sso-uuid",
                            LastName = "Resident28Last"
                        },
                        new
                        {
                            Id = 28,
                            ApartmentId = 21,
                            FirstName = "Resident29First",
                            KeycloakUserId = "resident-29-sso-uuid",
                            LastName = "Resident29Last"
                        },
                        new
                        {
                            Id = 29,
                            ApartmentId = 22,
                            FirstName = "Resident30First",
                            KeycloakUserId = "resident-30-sso-uuid",
                            LastName = "Resident30Last"
                        },
                        new
                        {
                            Id = 30,
                            ApartmentId = 23,
                            FirstName = "Resident31First",
                            KeycloakUserId = "resident-31-sso-uuid",
                            LastName = "Resident31Last"
                        },
                        new
                        {
                            Id = 31,
                            ApartmentId = 24,
                            FirstName = "Resident32First",
                            KeycloakUserId = "resident-32-sso-uuid",
                            LastName = "Resident32Last"
                        },
                        new
                        {
                            Id = 32,
                            ApartmentId = 24,
                            FirstName = "Resident33First",
                            KeycloakUserId = "resident-33-sso-uuid",
                            LastName = "Resident33Last"
                        },
                        new
                        {
                            Id = 33,
                            ApartmentId = 25,
                            FirstName = "Resident34First",
                            KeycloakUserId = "resident-34-sso-uuid",
                            LastName = "Resident34Last"
                        },
                        new
                        {
                            Id = 34,
                            ApartmentId = 26,
                            FirstName = "Resident35First",
                            KeycloakUserId = "resident-35-sso-uuid",
                            LastName = "Resident35Last"
                        },
                        new
                        {
                            Id = 35,
                            ApartmentId = 27,
                            FirstName = "Resident36First",
                            KeycloakUserId = "resident-36-sso-uuid",
                            LastName = "Resident36Last"
                        },
                        new
                        {
                            Id = 36,
                            ApartmentId = 27,
                            FirstName = "Resident37First",
                            KeycloakUserId = "resident-37-sso-uuid",
                            LastName = "Resident37Last"
                        },
                        new
                        {
                            Id = 37,
                            ApartmentId = 28,
                            FirstName = "Resident38First",
                            KeycloakUserId = "resident-38-sso-uuid",
                            LastName = "Resident38Last"
                        },
                        new
                        {
                            Id = 38,
                            ApartmentId = 29,
                            FirstName = "Resident39First",
                            KeycloakUserId = "resident-39-sso-uuid",
                            LastName = "Resident39Last"
                        },
                        new
                        {
                            Id = 39,
                            ApartmentId = 30,
                            FirstName = "Resident40First",
                            KeycloakUserId = "resident-40-sso-uuid",
                            LastName = "Resident40Last"
                        },
                        new
                        {
                            Id = 40,
                            ApartmentId = 30,
                            FirstName = "Resident41First",
                            KeycloakUserId = "resident-41-sso-uuid",
                            LastName = "Resident41Last"
                        },
                        new
                        {
                            Id = 41,
                            ApartmentId = 31,
                            FirstName = "Resident42First",
                            KeycloakUserId = "resident-42-sso-uuid",
                            LastName = "Resident42Last"
                        },
                        new
                        {
                            Id = 42,
                            ApartmentId = 32,
                            FirstName = "Resident43First",
                            KeycloakUserId = "resident-43-sso-uuid",
                            LastName = "Resident43Last"
                        },
                        new
                        {
                            Id = 43,
                            ApartmentId = 33,
                            FirstName = "Resident44First",
                            KeycloakUserId = "resident-44-sso-uuid",
                            LastName = "Resident44Last"
                        },
                        new
                        {
                            Id = 44,
                            ApartmentId = 33,
                            FirstName = "Resident45First",
                            KeycloakUserId = "resident-45-sso-uuid",
                            LastName = "Resident45Last"
                        },
                        new
                        {
                            Id = 45,
                            ApartmentId = 34,
                            FirstName = "Resident46First",
                            KeycloakUserId = "resident-46-sso-uuid",
                            LastName = "Resident46Last"
                        },
                        new
                        {
                            Id = 46,
                            ApartmentId = 35,
                            FirstName = "Resident47First",
                            KeycloakUserId = "resident-47-sso-uuid",
                            LastName = "Resident47Last"
                        },
                        new
                        {
                            Id = 47,
                            ApartmentId = 36,
                            FirstName = "Resident48First",
                            KeycloakUserId = "resident-48-sso-uuid",
                            LastName = "Resident48Last"
                        },
                        new
                        {
                            Id = 48,
                            ApartmentId = 36,
                            FirstName = "Resident49First",
                            KeycloakUserId = "resident-49-sso-uuid",
                            LastName = "Resident49Last"
                        },
                        new
                        {
                            Id = 49,
                            ApartmentId = 37,
                            FirstName = "Resident50First",
                            KeycloakUserId = "resident-50-sso-uuid",
                            LastName = "Resident50Last"
                        },
                        new
                        {
                            Id = 50,
                            ApartmentId = 38,
                            FirstName = "Resident51First",
                            KeycloakUserId = "resident-51-sso-uuid",
                            LastName = "Resident51Last"
                        },
                        new
                        {
                            Id = 51,
                            ApartmentId = 39,
                            FirstName = "Resident52First",
                            KeycloakUserId = "resident-52-sso-uuid",
                            LastName = "Resident52Last"
                        },
                        new
                        {
                            Id = 52,
                            ApartmentId = 39,
                            FirstName = "Resident53First",
                            KeycloakUserId = "resident-53-sso-uuid",
                            LastName = "Resident53Last"
                        },
                        new
                        {
                            Id = 53,
                            ApartmentId = 40,
                            FirstName = "Resident54First",
                            KeycloakUserId = "resident-54-sso-uuid",
                            LastName = "Resident54Last"
                        },
                        new
                        {
                            Id = 54,
                            ApartmentId = 41,
                            FirstName = "Resident55First",
                            KeycloakUserId = "resident-55-sso-uuid",
                            LastName = "Resident55Last"
                        },
                        new
                        {
                            Id = 55,
                            ApartmentId = 42,
                            FirstName = "Resident56First",
                            KeycloakUserId = "resident-56-sso-uuid",
                            LastName = "Resident56Last"
                        },
                        new
                        {
                            Id = 56,
                            ApartmentId = 42,
                            FirstName = "Resident57First",
                            KeycloakUserId = "resident-57-sso-uuid",
                            LastName = "Resident57Last"
                        },
                        new
                        {
                            Id = 57,
                            ApartmentId = 43,
                            FirstName = "Resident58First",
                            KeycloakUserId = "resident-58-sso-uuid",
                            LastName = "Resident58Last"
                        },
                        new
                        {
                            Id = 58,
                            ApartmentId = 44,
                            FirstName = "Resident59First",
                            KeycloakUserId = "resident-59-sso-uuid",
                            LastName = "Resident59Last"
                        },
                        new
                        {
                            Id = 59,
                            ApartmentId = 45,
                            FirstName = "Resident60First",
                            KeycloakUserId = "resident-60-sso-uuid",
                            LastName = "Resident60Last"
                        },
                        new
                        {
                            Id = 60,
                            ApartmentId = 45,
                            FirstName = "Resident61First",
                            KeycloakUserId = "resident-61-sso-uuid",
                            LastName = "Resident61Last"
                        });
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("ApartmentManager", b =>
                {
                    b.HasOne("VastGrid.Server.Models.Entities.Apartment", null)
                        .WithMany()
                        .HasForeignKey("ApartmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VastGrid.Server.Models.Entities.Manager", null)
                        .WithMany()
                        .HasForeignKey("ManagersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.Apartment", b =>
                {
                    b.HasOne("VastGrid.Server.Models.Entities.Builder", "Builder")
                        .WithMany("Apartments")
                        .HasForeignKey("BuilderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Builder");
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.Resident", b =>
                {
                    b.HasOne("VastGrid.Server.Models.Entities.Apartment", "Apartment")
                        .WithMany("Residents")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.Apartment", b =>
                {
                    b.Navigation("Residents");
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.Builder", b =>
                {
                    b.Navigation("Apartments");
                });
#pragma warning restore 612, 618
        }
    }
}
