// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VastGrid.Server.Data;

#nullable disable

namespace VastGrid.Server.Migrations
{
    [DbContext(typeof(VastGridDbContext))]
    [Migration("20260522151609_SeedSampleData")]
    partial class SeedSampleData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApartmentManager", b =>
                {
                    b.Property<int>("ApartmentsId")
                        .HasColumnType("integer");

                    b.Property<int>("ManagersId")
                        .HasColumnType("integer");

                    b.HasKey("ApartmentsId", "ManagersId");

                    b.HasIndex("ManagersId");

                    b.ToTable("ApartmentManagers", (string)null);

                    b.HasData(
                        new
                        {
                            ApartmentsId = 1,
                            ManagersId = 1
                        },
                        new
                        {
                            ApartmentsId = 2,
                            ManagersId = 1
                        });
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BlockName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BuilderId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("boolean");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BuilderId");

                    b.ToTable("Apartments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlockName = "Block A",
                            BuilderId = 1,
                            IsOccupied = true,
                            UnitNumber = "101"
                        },
                        new
                        {
                            Id = 2,
                            BlockName = "Block B",
                            BuilderId = 1,
                            IsOccupied = false,
                            UnitNumber = "205"
                        },
                        new
                        {
                            Id = 3,
                            BlockName = "Tower C",
                            BuilderId = 2,
                            IsOccupied = true,
                            UnitNumber = "Penthouse 1"
                        });
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.Builder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Builders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Aura Properties",
                            ContactEmail = "contact@auraproperties.com"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Skyline Dev",
                            ContactEmail = "hello@skylinedev.com"
                        });
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeycloakUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Alice",
                            KeycloakUserId = "alice-manager-uuid",
                            LastName = "Johnson"
                        });
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.Resident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeycloakUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.ToTable("Residents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApartmentId = 1,
                            FirstName = "John",
                            KeycloakUserId = "john-sso-uuid",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            ApartmentId = 3,
                            FirstName = "Jane",
                            KeycloakUserId = "jane-sso-uuid",
                            LastName = "Smith"
                        });
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("ApartmentManager", b =>
                {
                    b.HasOne("VastGrid.Server.Models.Entities.Apartment", null)
                        .WithMany()
                        .HasForeignKey("ApartmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VastGrid.Server.Models.Entities.Manager", null)
                        .WithMany()
                        .HasForeignKey("ManagersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.Apartment", b =>
                {
                    b.HasOne("VastGrid.Server.Models.Entities.Builder", "Builder")
                        .WithMany("Apartments")
                        .HasForeignKey("BuilderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Builder");
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.Resident", b =>
                {
                    b.HasOne("VastGrid.Server.Models.Entities.Apartment", "Apartment")
                        .WithMany("Residents")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.Apartment", b =>
                {
                    b.Navigation("Residents");
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.Builder", b =>
                {
                    b.Navigation("Apartments");
                });
#pragma warning restore 612, 618
        }
    }
}
