// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VastGrid.Server.Data;

#nullable disable

namespace VastGrid.Server.Migrations
{
    [DbContext(typeof(VastGridDbContext))]
    [Migration("20260524005817_AuraAIAndGateKeeper")]
    partial class AuraAIAndGateKeeper
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApartmentManager", b =>
                {
                    b.Property<int>("ApartmentsId")
                        .HasColumnType("integer");

                    b.Property<int>("ManagersId")
                        .HasColumnType("integer");

                    b.HasKey("ApartmentsId", "ManagersId");

                    b.HasIndex("ManagersId");

                    b.ToTable("ApartmentManagers", (string)null);

                    b.HasData(
                        new
                        {
                            ApartmentsId = 1,
                            ManagersId = 1
                        },
                        new
                        {
                            ApartmentsId = 2,
                            ManagersId = 1
                        },
                        new
                        {
                            ApartmentsId = 3,
                            ManagersId = 1
                        },
                        new
                        {
                            ApartmentsId = 4,
                            ManagersId = 1
                        },
                        new
                        {
                            ApartmentsId = 5,
                            ManagersId = 1
                        },
                        new
                        {
                            ApartmentsId = 6,
                            ManagersId = 2
                        },
                        new
                        {
                            ApartmentsId = 6,
                            ManagersId = 5
                        },
                        new
                        {
                            ApartmentsId = 1,
                            ManagersId = 6
                        },
                        new
                        {
                            ApartmentsId = 2,
                            ManagersId = 7
                        },
                        new
                        {
                            ApartmentsId = 3,
                            ManagersId = 8
                        },
                        new
                        {
                            ApartmentsId = 4,
                            ManagersId = 9
                        },
                        new
                        {
                            ApartmentsId = 5,
                            ManagersId = 10
                        },
                        new
                        {
                            ApartmentsId = 6,
                            ManagersId = 11
                        },
                        new
                        {
                            ApartmentsId = 1,
                            ManagersId = 12
                        },
                        new
                        {
                            ApartmentsId = 2,
                            ManagersId = 13
                        },
                        new
                        {
                            ApartmentsId = 3,
                            ManagersId = 14
                        },
                        new
                        {
                            ApartmentsId = 4,
                            ManagersId = 15
                        });
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BlockName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BuilderId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalFlats")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuilderId");

                    b.ToTable("Apartments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlockName = "Block A",
                            BuilderId = 1,
                            TotalFlats = 50
                        },
                        new
                        {
                            Id = 2,
                            BlockName = "Block B",
                            BuilderId = 1,
                            TotalFlats = 50
                        },
                        new
                        {
                            Id = 3,
                            BlockName = "Block C",
                            BuilderId = 2,
                            TotalFlats = 50
                        },
                        new
                        {
                            Id = 4,
                            BlockName = "Block D",
                            BuilderId = 2,
                            TotalFlats = 50
                        },
                        new
                        {
                            Id = 5,
                            BlockName = "Block E",
                            BuilderId = 3,
                            TotalFlats = 50
                        },
                        new
                        {
                            Id = 6,
                            BlockName = "Block F",
                            BuilderId = 3,
                            TotalFlats = 50
                        });
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.Builder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeycloakUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Builders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Aura Properties",
                            ContactEmail = "builder@vastgrid.local",
                            KeycloakUserId = "dev-builder-sub"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Skyline Dev",
                            ContactEmail = "skyline@vastgrid.local"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Pinnacle Real Estate",
                            ContactEmail = "pinnacle@vastgrid.local"
                        });
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeycloakUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Manager1First",
                            KeycloakUserId = "manager-1-sso-uuid",
                            LastName = "Manager1Last"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Manager2First",
                            KeycloakUserId = "manager-2-sso-uuid",
                            LastName = "Manager2Last"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Manager3First",
                            KeycloakUserId = "manager-3-sso-uuid",
                            LastName = "Manager3Last"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Manager4First",
                            KeycloakUserId = "manager-4-sso-uuid",
                            LastName = "Manager4Last"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Manager5First",
                            KeycloakUserId = "manager-5-sso-uuid",
                            LastName = "Manager5Last"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Manager6First",
                            KeycloakUserId = "manager-6-sso-uuid",
                            LastName = "Manager6Last"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Manager7First",
                            KeycloakUserId = "manager-7-sso-uuid",
                            LastName = "Manager7Last"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Manager8First",
                            KeycloakUserId = "manager-8-sso-uuid",
                            LastName = "Manager8Last"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Manager9First",
                            KeycloakUserId = "manager-9-sso-uuid",
                            LastName = "Manager9Last"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Manager10First",
                            KeycloakUserId = "manager-10-sso-uuid",
                            LastName = "Manager10Last"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Manager11First",
                            KeycloakUserId = "manager-11-sso-uuid",
                            LastName = "Manager11Last"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Manager12First",
                            KeycloakUserId = "manager-12-sso-uuid",
                            LastName = "Manager12Last"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Manager13First",
                            KeycloakUserId = "manager-13-sso-uuid",
                            LastName = "Manager13Last"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Manager14First",
                            KeycloakUserId = "manager-14-sso-uuid",
                            LastName = "Manager14Last"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Manager15First",
                            KeycloakUserId = "manager-15-sso-uuid",
                            LastName = "Manager15Last"
                        });
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.Resident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeycloakUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.ToTable("Residents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApartmentId = 1,
                            FirstName = "Resident2First",
                            KeycloakUserId = "resident-2-sso-uuid",
                            LastName = "Resident2Last",
                            PhoneNumber = "+91 9800000002"
                        },
                        new
                        {
                            Id = 2,
                            ApartmentId = 1,
                            FirstName = "Resident3First",
                            KeycloakUserId = "resident-3-sso-uuid",
                            LastName = "Resident3Last",
                            PhoneNumber = "+91 9800000003"
                        },
                        new
                        {
                            Id = 3,
                            ApartmentId = 1,
                            FirstName = "Resident4First",
                            KeycloakUserId = "resident-4-sso-uuid",
                            LastName = "Resident4Last",
                            PhoneNumber = "+91 9800000004"
                        },
                        new
                        {
                            Id = 4,
                            ApartmentId = 1,
                            FirstName = "Resident5First",
                            KeycloakUserId = "resident-5-sso-uuid",
                            LastName = "Resident5Last",
                            PhoneNumber = "+91 9800000005"
                        },
                        new
                        {
                            Id = 5,
                            ApartmentId = 1,
                            FirstName = "Resident6First",
                            KeycloakUserId = "resident-6-sso-uuid",
                            LastName = "Resident6Last",
                            PhoneNumber = "+91 9800000006"
                        },
                        new
                        {
                            Id = 6,
                            ApartmentId = 1,
                            FirstName = "Resident7First",
                            KeycloakUserId = "resident-7-sso-uuid",
                            LastName = "Resident7Last",
                            PhoneNumber = "+91 9800000007"
                        },
                        new
                        {
                            Id = 7,
                            ApartmentId = 1,
                            FirstName = "Resident8First",
                            KeycloakUserId = "resident-8-sso-uuid",
                            LastName = "Resident8Last",
                            PhoneNumber = "+91 9800000008"
                        },
                        new
                        {
                            Id = 8,
                            ApartmentId = 2,
                            FirstName = "Resident9First",
                            KeycloakUserId = "resident-9-sso-uuid",
                            LastName = "Resident9Last",
                            PhoneNumber = "+91 9800000009"
                        },
                        new
                        {
                            Id = 9,
                            ApartmentId = 2,
                            FirstName = "Resident10First",
                            KeycloakUserId = "resident-10-sso-uuid",
                            LastName = "Resident10Last",
                            PhoneNumber = "+91 9800000010"
                        },
                        new
                        {
                            Id = 10,
                            ApartmentId = 2,
                            FirstName = "Resident11First",
                            KeycloakUserId = "resident-11-sso-uuid",
                            LastName = "Resident11Last",
                            PhoneNumber = "+91 9800000011"
                        },
                        new
                        {
                            Id = 11,
                            ApartmentId = 2,
                            FirstName = "Resident12First",
                            KeycloakUserId = "resident-12-sso-uuid",
                            LastName = "Resident12Last",
                            PhoneNumber = "+91 9800000012"
                        },
                        new
                        {
                            Id = 12,
                            ApartmentId = 2,
                            FirstName = "Resident13First",
                            KeycloakUserId = "resident-13-sso-uuid",
                            LastName = "Resident13Last",
                            PhoneNumber = "+91 9800000013"
                        },
                        new
                        {
                            Id = 13,
                            ApartmentId = 2,
                            FirstName = "Resident14First",
                            KeycloakUserId = "resident-14-sso-uuid",
                            LastName = "Resident14Last",
                            PhoneNumber = "+91 9800000014"
                        },
                        new
                        {
                            Id = 14,
                            ApartmentId = 2,
                            FirstName = "Resident15First",
                            KeycloakUserId = "resident-15-sso-uuid",
                            LastName = "Resident15Last",
                            PhoneNumber = "+91 9800000015"
                        },
                        new
                        {
                            Id = 15,
                            ApartmentId = 2,
                            FirstName = "Resident16First",
                            KeycloakUserId = "resident-16-sso-uuid",
                            LastName = "Resident16Last",
                            PhoneNumber = "+91 9800000016"
                        },
                        new
                        {
                            Id = 16,
                            ApartmentId = 2,
                            FirstName = "Resident17First",
                            KeycloakUserId = "resident-17-sso-uuid",
                            LastName = "Resident17Last",
                            PhoneNumber = "+91 9800000017"
                        },
                        new
                        {
                            Id = 17,
                            ApartmentId = 3,
                            FirstName = "Resident18First",
                            KeycloakUserId = "resident-18-sso-uuid",
                            LastName = "Resident18Last",
                            PhoneNumber = "+91 9800000018"
                        },
                        new
                        {
                            Id = 18,
                            ApartmentId = 3,
                            FirstName = "Resident19First",
                            KeycloakUserId = "resident-19-sso-uuid",
                            LastName = "Resident19Last",
                            PhoneNumber = "+91 9800000019"
                        },
                        new
                        {
                            Id = 19,
                            ApartmentId = 3,
                            FirstName = "Resident20First",
                            KeycloakUserId = "resident-20-sso-uuid",
                            LastName = "Resident20Last",
                            PhoneNumber = "+91 9800000020"
                        },
                        new
                        {
                            Id = 20,
                            ApartmentId = 3,
                            FirstName = "Resident21First",
                            KeycloakUserId = "resident-21-sso-uuid",
                            LastName = "Resident21Last",
                            PhoneNumber = "+91 9800000021"
                        },
                        new
                        {
                            Id = 21,
                            ApartmentId = 3,
                            FirstName = "Resident22First",
                            KeycloakUserId = "resident-22-sso-uuid",
                            LastName = "Resident22Last",
                            PhoneNumber = "+91 9800000022"
                        },
                        new
                        {
                            Id = 22,
                            ApartmentId = 3,
                            FirstName = "Resident23First",
                            KeycloakUserId = "resident-23-sso-uuid",
                            LastName = "Resident23Last",
                            PhoneNumber = "+91 9800000023"
                        },
                        new
                        {
                            Id = 23,
                            ApartmentId = 3,
                            FirstName = "Resident24First",
                            KeycloakUserId = "resident-24-sso-uuid",
                            LastName = "Resident24Last",
                            PhoneNumber = "+91 9800000024"
                        },
                        new
                        {
                            Id = 24,
                            ApartmentId = 3,
                            FirstName = "Resident25First",
                            KeycloakUserId = "resident-25-sso-uuid",
                            LastName = "Resident25Last",
                            PhoneNumber = "+91 9800000025"
                        },
                        new
                        {
                            Id = 25,
                            ApartmentId = 3,
                            FirstName = "Resident26First",
                            KeycloakUserId = "resident-26-sso-uuid",
                            LastName = "Resident26Last",
                            PhoneNumber = "+91 9800000026"
                        },
                        new
                        {
                            Id = 26,
                            ApartmentId = 3,
                            FirstName = "Resident27First",
                            KeycloakUserId = "resident-27-sso-uuid",
                            LastName = "Resident27Last",
                            PhoneNumber = "+91 9800000027"
                        },
                        new
                        {
                            Id = 27,
                            ApartmentId = 3,
                            FirstName = "Resident28First",
                            KeycloakUserId = "resident-28-sso-uuid",
                            LastName = "Resident28Last",
                            PhoneNumber = "+91 9800000028"
                        },
                        new
                        {
                            Id = 28,
                            ApartmentId = 4,
                            FirstName = "Resident29First",
                            KeycloakUserId = "resident-29-sso-uuid",
                            LastName = "Resident29Last",
                            PhoneNumber = "+91 9800000029"
                        },
                        new
                        {
                            Id = 29,
                            ApartmentId = 4,
                            FirstName = "Resident30First",
                            KeycloakUserId = "resident-30-sso-uuid",
                            LastName = "Resident30Last",
                            PhoneNumber = "+91 9800000030"
                        },
                        new
                        {
                            Id = 30,
                            ApartmentId = 4,
                            FirstName = "Resident31First",
                            KeycloakUserId = "resident-31-sso-uuid",
                            LastName = "Resident31Last",
                            PhoneNumber = "+91 9800000031"
                        },
                        new
                        {
                            Id = 31,
                            ApartmentId = 4,
                            FirstName = "Resident32First",
                            KeycloakUserId = "resident-32-sso-uuid",
                            LastName = "Resident32Last",
                            PhoneNumber = "+91 9800000032"
                        },
                        new
                        {
                            Id = 32,
                            ApartmentId = 4,
                            FirstName = "Resident33First",
                            KeycloakUserId = "resident-33-sso-uuid",
                            LastName = "Resident33Last",
                            PhoneNumber = "+91 9800000033"
                        },
                        new
                        {
                            Id = 33,
                            ApartmentId = 4,
                            FirstName = "Resident34First",
                            KeycloakUserId = "resident-34-sso-uuid",
                            LastName = "Resident34Last",
                            PhoneNumber = "+91 9800000034"
                        },
                        new
                        {
                            Id = 34,
                            ApartmentId = 4,
                            FirstName = "Resident35First",
                            KeycloakUserId = "resident-35-sso-uuid",
                            LastName = "Resident35Last",
                            PhoneNumber = "+91 9800000035"
                        },
                        new
                        {
                            Id = 35,
                            ApartmentId = 4,
                            FirstName = "Resident36First",
                            KeycloakUserId = "resident-36-sso-uuid",
                            LastName = "Resident36Last",
                            PhoneNumber = "+91 9800000036"
                        },
                        new
                        {
                            Id = 36,
                            ApartmentId = 4,
                            FirstName = "Resident37First",
                            KeycloakUserId = "resident-37-sso-uuid",
                            LastName = "Resident37Last",
                            PhoneNumber = "+91 9800000037"
                        },
                        new
                        {
                            Id = 37,
                            ApartmentId = 4,
                            FirstName = "Resident38First",
                            KeycloakUserId = "resident-38-sso-uuid",
                            LastName = "Resident38Last",
                            PhoneNumber = "+91 9800000038"
                        },
                        new
                        {
                            Id = 38,
                            ApartmentId = 4,
                            FirstName = "Resident39First",
                            KeycloakUserId = "resident-39-sso-uuid",
                            LastName = "Resident39Last",
                            PhoneNumber = "+91 9800000039"
                        },
                        new
                        {
                            Id = 39,
                            ApartmentId = 4,
                            FirstName = "Resident40First",
                            KeycloakUserId = "resident-40-sso-uuid",
                            LastName = "Resident40Last",
                            PhoneNumber = "+91 9800000040"
                        },
                        new
                        {
                            Id = 40,
                            ApartmentId = 4,
                            FirstName = "Resident41First",
                            KeycloakUserId = "resident-41-sso-uuid",
                            LastName = "Resident41Last",
                            PhoneNumber = "+91 9800000041"
                        },
                        new
                        {
                            Id = 41,
                            ApartmentId = 5,
                            FirstName = "Resident42First",
                            KeycloakUserId = "resident-42-sso-uuid",
                            LastName = "Resident42Last",
                            PhoneNumber = "+91 9800000042"
                        },
                        new
                        {
                            Id = 42,
                            ApartmentId = 5,
                            FirstName = "Resident43First",
                            KeycloakUserId = "resident-43-sso-uuid",
                            LastName = "Resident43Last",
                            PhoneNumber = "+91 9800000043"
                        },
                        new
                        {
                            Id = 43,
                            ApartmentId = 5,
                            FirstName = "Resident44First",
                            KeycloakUserId = "resident-44-sso-uuid",
                            LastName = "Resident44Last",
                            PhoneNumber = "+91 9800000044"
                        },
                        new
                        {
                            Id = 44,
                            ApartmentId = 5,
                            FirstName = "Resident45First",
                            KeycloakUserId = "resident-45-sso-uuid",
                            LastName = "Resident45Last",
                            PhoneNumber = "+91 9800000045"
                        },
                        new
                        {
                            Id = 45,
                            ApartmentId = 5,
                            FirstName = "Resident46First",
                            KeycloakUserId = "resident-46-sso-uuid",
                            LastName = "Resident46Last",
                            PhoneNumber = "+91 9800000046"
                        },
                        new
                        {
                            Id = 46,
                            ApartmentId = 5,
                            FirstName = "Resident47First",
                            KeycloakUserId = "resident-47-sso-uuid",
                            LastName = "Resident47Last",
                            PhoneNumber = "+91 9800000047"
                        },
                        new
                        {
                            Id = 47,
                            ApartmentId = 5,
                            FirstName = "Resident48First",
                            KeycloakUserId = "resident-48-sso-uuid",
                            LastName = "Resident48Last",
                            PhoneNumber = "+91 9800000048"
                        },
                        new
                        {
                            Id = 48,
                            ApartmentId = 5,
                            FirstName = "Resident49First",
                            KeycloakUserId = "resident-49-sso-uuid",
                            LastName = "Resident49Last",
                            PhoneNumber = "+91 9800000049"
                        },
                        new
                        {
                            Id = 49,
                            ApartmentId = 5,
                            FirstName = "Resident50First",
                            KeycloakUserId = "resident-50-sso-uuid",
                            LastName = "Resident50Last",
                            PhoneNumber = "+91 9800000050"
                        },
                        new
                        {
                            Id = 50,
                            ApartmentId = 5,
                            FirstName = "Resident51First",
                            KeycloakUserId = "resident-51-sso-uuid",
                            LastName = "Resident51Last",
                            PhoneNumber = "+91 9800000051"
                        },
                        new
                        {
                            Id = 51,
                            ApartmentId = 5,
                            FirstName = "Resident52First",
                            KeycloakUserId = "resident-52-sso-uuid",
                            LastName = "Resident52Last",
                            PhoneNumber = "+91 9800000052"
                        },
                        new
                        {
                            Id = 52,
                            ApartmentId = 5,
                            FirstName = "Resident53First",
                            KeycloakUserId = "resident-53-sso-uuid",
                            LastName = "Resident53Last",
                            PhoneNumber = "+91 9800000053"
                        },
                        new
                        {
                            Id = 53,
                            ApartmentId = 5,
                            FirstName = "Resident54First",
                            KeycloakUserId = "resident-54-sso-uuid",
                            LastName = "Resident54Last",
                            PhoneNumber = "+91 9800000054"
                        },
                        new
                        {
                            Id = 54,
                            ApartmentId = 5,
                            FirstName = "Resident55First",
                            KeycloakUserId = "resident-55-sso-uuid",
                            LastName = "Resident55Last",
                            PhoneNumber = "+91 9800000055"
                        },
                        new
                        {
                            Id = 55,
                            ApartmentId = 5,
                            FirstName = "Resident56First",
                            KeycloakUserId = "resident-56-sso-uuid",
                            LastName = "Resident56Last",
                            PhoneNumber = "+91 9800000056"
                        },
                        new
                        {
                            Id = 56,
                            ApartmentId = 6,
                            FirstName = "Resident57First",
                            KeycloakUserId = "resident-57-sso-uuid",
                            LastName = "Resident57Last",
                            PhoneNumber = "+91 9800000057"
                        },
                        new
                        {
                            Id = 57,
                            ApartmentId = 6,
                            FirstName = "Resident58First",
                            KeycloakUserId = "resident-58-sso-uuid",
                            LastName = "Resident58Last",
                            PhoneNumber = "+91 9800000058"
                        },
                        new
                        {
                            Id = 58,
                            ApartmentId = 6,
                            FirstName = "Resident59First",
                            KeycloakUserId = "resident-59-sso-uuid",
                            LastName = "Resident59Last",
                            PhoneNumber = "+91 9800000059"
                        },
                        new
                        {
                            Id = 59,
                            ApartmentId = 6,
                            FirstName = "Resident60First",
                            KeycloakUserId = "resident-60-sso-uuid",
                            LastName = "Resident60Last",
                            PhoneNumber = "+91 9800000060"
                        },
                        new
                        {
                            Id = 60,
                            ApartmentId = 6,
                            FirstName = "Resident61First",
                            KeycloakUserId = "resident-61-sso-uuid",
                            LastName = "Resident61Last",
                            PhoneNumber = "+91 9800000061"
                        },
                        new
                        {
                            Id = 61,
                            ApartmentId = 6,
                            FirstName = "Resident62First",
                            KeycloakUserId = "resident-62-sso-uuid",
                            LastName = "Resident62Last",
                            PhoneNumber = "+91 9800000062"
                        },
                        new
                        {
                            Id = 62,
                            ApartmentId = 6,
                            FirstName = "Resident63First",
                            KeycloakUserId = "resident-63-sso-uuid",
                            LastName = "Resident63Last",
                            PhoneNumber = "+91 9800000063"
                        },
                        new
                        {
                            Id = 63,
                            ApartmentId = 6,
                            FirstName = "Resident64First",
                            KeycloakUserId = "resident-64-sso-uuid",
                            LastName = "Resident64Last",
                            PhoneNumber = "+91 9800000064"
                        },
                        new
                        {
                            Id = 64,
                            ApartmentId = 6,
                            FirstName = "Resident65First",
                            KeycloakUserId = "resident-65-sso-uuid",
                            LastName = "Resident65Last",
                            PhoneNumber = "+91 9800000065"
                        },
                        new
                        {
                            Id = 65,
                            ApartmentId = 6,
                            FirstName = "Resident66First",
                            KeycloakUserId = "resident-66-sso-uuid",
                            LastName = "Resident66Last",
                            PhoneNumber = "+91 9800000066"
                        },
                        new
                        {
                            Id = 66,
                            ApartmentId = 6,
                            FirstName = "Resident67First",
                            KeycloakUserId = "resident-67-sso-uuid",
                            LastName = "Resident67Last",
                            PhoneNumber = "+91 9800000067"
                        },
                        new
                        {
                            Id = 67,
                            ApartmentId = 6,
                            FirstName = "Resident68First",
                            KeycloakUserId = "resident-68-sso-uuid",
                            LastName = "Resident68Last",
                            PhoneNumber = "+91 9800000068"
                        },
                        new
                        {
                            Id = 68,
                            ApartmentId = 6,
                            FirstName = "Resident69First",
                            KeycloakUserId = "resident-69-sso-uuid",
                            LastName = "Resident69Last",
                            PhoneNumber = "+91 9800000069"
                        },
                        new
                        {
                            Id = 69,
                            ApartmentId = 6,
                            FirstName = "Resident70First",
                            KeycloakUserId = "resident-70-sso-uuid",
                            LastName = "Resident70Last",
                            PhoneNumber = "+91 9800000070"
                        },
                        new
                        {
                            Id = 70,
                            ApartmentId = 6,
                            FirstName = "Resident71First",
                            KeycloakUserId = "resident-71-sso-uuid",
                            LastName = "Resident71Last",
                            PhoneNumber = "+91 9800000071"
                        },
                        new
                        {
                            Id = 71,
                            ApartmentId = 6,
                            FirstName = "Resident72First",
                            KeycloakUserId = "resident-72-sso-uuid",
                            LastName = "Resident72Last",
                            PhoneNumber = "+91 9800000072"
                        },
                        new
                        {
                            Id = 72,
                            ApartmentId = 6,
                            FirstName = "Resident73First",
                            KeycloakUserId = "resident-73-sso-uuid",
                            LastName = "Resident73Last",
                            PhoneNumber = "+91 9800000073"
                        });
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiagnosisResult")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ResidentId")
                        .HasColumnType("integer");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("ResidentId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.VisitorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ResidentId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VisitorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WatchmanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.ToTable("VisitorLogs");
                });

            modelBuilder.Entity("ApartmentManager", b =>
                {
                    b.HasOne("VastGrid.Server.Models.Entities.Apartment", null)
                        .WithMany()
                        .HasForeignKey("ApartmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VastGrid.Server.Models.Entities.Manager", null)
                        .WithMany()
                        .HasForeignKey("ManagersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.Apartment", b =>
                {
                    b.HasOne("VastGrid.Server.Models.Entities.Builder", "Builder")
                        .WithMany("Apartments")
                        .HasForeignKey("BuilderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Builder");
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.Resident", b =>
                {
                    b.HasOne("VastGrid.Server.Models.Entities.Apartment", "Apartment")
                        .WithMany("Residents")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.Ticket", b =>
                {
                    b.HasOne("VastGrid.Server.Models.Entities.Apartment", "Apartment")
                        .WithMany("Tickets")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VastGrid.Server.Models.Entities.Resident", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.VisitorLog", b =>
                {
                    b.HasOne("VastGrid.Server.Models.Entities.Resident", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.Apartment", b =>
                {
                    b.Navigation("Residents");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("VastGrid.Server.Models.Entities.Builder", b =>
                {
                    b.Navigation("Apartments");
                });
#pragma warning restore 612, 618
        }
    }
}
